import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./ui/theme-provider";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Header from "./ui/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gradient-to-br from-white via-blue-50 to-blue-100 text-gray-900">
<ClerkProvider >

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            <ConvexClientProvider>
              
           { /*header*/}
           <Header />
          
        <main className="relative min-h-screen container mx-auto pt-40 md:pt-32">
          {/*gl0w*/}
          <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
             <div className="absolute top-0 left-1/4 w-96 h-96 bg-pink-800/20 rounded-full blur-3xl" />
                  <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-blue-600/20 rounded-full blur-3xl" />
          </div>
          <div className="relative z-10 min-h-[70vh]">{children}</div>

          {/*footer*/}
          <footer className="border-t border-gray-200 py-4 px-6 max-w-7xl">
            <div className="text-sm text-gray-500">Created by ish</div>
          </footer>
          <Toaster position='top-center' richColors/>
          </main>
          
          </ConvexClientProvider>
         
            </ThemeProvider>
             </ClerkProvider>
      </body>
    </html>
  );
}
